### ISSUE TITLE
Acknowlage the existence of infinite grid interpreters?

### ISSUE THREAD

**Issue by Jachdich** [catseye/Befunge-93#32]
Although not strictly compliant to the Befunge 93 spec, there are numerous Befunge interpreters (including mine) that do not include the wrapping feature as they have effectively infinite grids. I'd like to propose a variation on Befunge 93 that acknowledges this fact.

**Comment by Dash-Lambda** [comment]
The toroidal mapping is one of the most fundamental parts of Befunge-93. There are later versions of Befunge that introduce infinite program spaces, but the common feature is still same-line wrapping once you reach the bounds of the existing program.

There's nothing wrong with making a derivative language, but since the program has a fundamentally different topology it shouldn't be considered just a variant of Befunge-93.

**Comment by cpressey** [comment]
Anyone is of course welcome to define their own variation on Befunge-93, and many people have.

It is not however within the scope of the Befunge-93 language project to catalogue all these variations.

But there *is* a project which *does* make it its business to catalogue these sorts of things: [the esolangs.org wiki](https://esolangs.org/wiki/).  It would be entirely appropriate to make note of any variant of Befunge-93 in [the "Related languages" section of the Befunge article there](https://esolangs.org/wiki/Befunge#Related_languages).

Have a great day!

**Comment by Jachdich** [comment]
Thanks for the suggestion, I understand now why that is not within the scope of this document. I will define a custom befunge 93 implementation and put it on esolangs.org
